export const testimonials = [{
        id: 1,
        name: "Veronica",
        comment: "GOOD APLICATION",
        time: "2 Days Ago",
        rating: 3,
        img: "image1",
    },
    {
        id: 2,
        name: "Nadine",
        comment: "Better Space make my working experience better",
        time: "3 Days Ago",
        rating: 4.5,
        img: "image2",
    },
    {
        id: 3,
        name: "Agustie",
        comment: "Work life balance",
        time: "3 Days Ago",
        rating: 3,
        img: "image3",
    },
    {
        id: 4,
        name: "Antonius",
        comment: "Easy booking, i like it!",
        time: "5 Days Ago",
        rating: 4,
        img: "image4",
    },
    {
        id: 5,
        name: "Jasmine",
        comment: "Awesome apps ! i love it",
        time: "Today",
        rating: 5,
        img: "image5",
    },
    {
        id: 6,
        name: "Salsa",
        comment: "Before i know this apps, i felt so confuse",
        time: "1 weeks Ago",
        rating: 5,
        img: "image6",
    },
    {
        id: 7,
        name: "Dion",
        comment: "Make my life easier!",
        time: "1 Days Ago",
        rating: 4.5,
        img: "image7",
    },
    {
        id: 8,
        name: "Bernadi",
        comment: "I got an amazing workspace in South Jakarta",
        time: "1 Days Ago",
        rating: 3,
        img: "image8",
    },
    {
        id: 9,
        name: "Antonius",
        comment: "It can be better if there were a game play",
        time: "1 Days Ago",
        rating: 4,
        img: "image9",
    },
    {
        id: 10,
        name: "Layla",
        comment: "I always use this application before working",
        time: "2 Days Ago",
        rating: 4.5,
        img: "image10",
    },
];