export const dataJakarta = [
  {
    city: "Central Jakarta",
    district: [
      "Cempaka Putih",
      "Gambir",
      "Johar Baru",
      "Kemayoran",
      "Menteng",
      "Sawah Besar",
      "Senen",
      "Tanah Abang",
    ],
  },
  {
    city: "South Jakarta",
    district: [
      "Cilandak",
      "Jagakarsa",
      "Kebayoran Baru",
      "Kebayoran Lama",
      "Mampang Prapatan",
      "Pancoran",
      "Pasar Minggu",
      "Pesanggrahan",
      "Setia Budi",
      "Tebet",
    ],
  },
  {
    city: "West Jakarta",
    district: [
      "Cengkareng",
      "Grogol",
      "Kalideres",
      "Kebon Jeruk",
      "Kembangan",
      "Palmerah",
      "Taman Sari",
      "Tambora",
    ],
  },
  {
    city: "East Jakarta",
    district: [
      "Cakung",
      "Cipayung",
      "Ciracas",
      "Duren Sawir",
      "Jatinegara",
      "Keramat Jati",
      "Makasar",
      "Mataram",
      "Pasar Rebo",
      "Pulo Gadung",
    ],
  },
  {
    city: "Thousand Islands",
    district: ["Kep. Seribu Selatan", "Kep. Seribu Utara"],
  },
];
